# Generated by Django 6.0.5 on 2026-05-31 14:48

import django.db.models.deletion
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalGig',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('last_update', models.DateTimeField(blank=True, editable=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('datenotes', models.TextField(blank=True, null=True)),
                ('safe_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Unconfirmed'), (1, 'Confirmed'), (2, 'Canceled'), (3, 'Asking')], default=0)),
                ('email_changes', models.BooleanField(default=True)),
                ('public_description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('invite_occasionals', models.BooleanField(default=True)),
                ('was_reminded', models.BooleanField(default=False)),
                ('hide_from_calendar', models.BooleanField(default=False)),
                ('default_to_attending', models.BooleanField(default=False)),
                ('trashed_date', models.DateTimeField(blank=True, null=True)),
                ('setlist', models.TextField(blank=True, null=True)),
                ('setdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('safe_setdate', models.DateTimeField(blank=True, null=True)),
                ('safe_enddate', models.DateTimeField(blank=True, null=True)),
                ('is_full_day', models.BooleanField(default=False)),
                ('has_call_time', models.BooleanField(default=False)),
                ('has_set_time', models.BooleanField(default=False)),
                ('has_end_time', models.BooleanField(default=False)),
                ('dress', models.TextField(blank=True, null=True)),
                ('paid', models.TextField(blank=True, null=True)),
                ('postgig', models.TextField(blank=True, null=True)),
                ('leader_text', models.TextField(blank=True, null=True)),
                ('rsvp_by_date', models.DateTimeField(blank=True, null=True)),
                ('plans_locked', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical gig',
                'verbose_name_plural': 'historical gigs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'No Plan'), (1, 'Definitely'), (2, 'Probably'), (3, "Don't Know"), (4, 'Probably Not'), (5, "Can't Do It"), (6, 'Not Interested')], default=0)),
                ('status_changed', models.BooleanField(default=False)),
                ('feedback_value', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('datenotes', models.TextField(blank=True, null=True)),
                ('safe_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Unconfirmed'), (1, 'Confirmed'), (2, 'Canceled'), (3, 'Asking')], default=0)),
                ('email_changes', models.BooleanField(default=True)),
                ('public_description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('invite_occasionals', models.BooleanField(default=True)),
                ('was_reminded', models.BooleanField(default=False)),
                ('hide_from_calendar', models.BooleanField(default=False)),
                ('default_to_attending', models.BooleanField(default=False)),
                ('trashed_date', models.DateTimeField(blank=True, null=True)),
                ('setlist', models.TextField(blank=True, null=True)),
                ('setdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('safe_setdate', models.DateTimeField(blank=True, null=True)),
                ('safe_enddate', models.DateTimeField(blank=True, null=True)),
                ('is_full_day', models.BooleanField(default=False)),
                ('has_call_time', models.BooleanField(default=False)),
                ('has_set_time', models.BooleanField(default=False)),
                ('has_end_time', models.BooleanField(default=False)),
                ('dress', models.TextField(blank=True, null=True)),
                ('paid', models.TextField(blank=True, null=True)),
                ('postgig', models.TextField(blank=True, null=True)),
                ('leader_text', models.TextField(blank=True, null=True)),
                ('rsvp_by_date', models.DateTimeField(blank=True, null=True)),
                ('plans_locked', models.BooleanField(default=False)),
                ('cal_feed_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to='band.band')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
