# Generated by Django 6.0.5 on 2026-05-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('kind', models.IntegerField(choices=[(0, 'Daily'), (1, 'All Time'), (2, 'Daily Accumulate'), (3, 'Every')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BandMetric',
            fields=[
                ('metric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.metric')),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='band.band')),
            ],
            bases=('stats.metric',),
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('value', models.IntegerField(blank=True, default=0)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='stats.bandmetric')),
            ],
        ),
    ]
