# Generated by Django 6.0.5 on 2026-05-31 14:48

import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assoc',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assocs', to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
        migrations.AddField(
            model_name='assoc',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assocs', to='band.band'),
        ),
        migrations.AddField(
            model_name='section',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='band.band'),
        ),
        migrations.AddField(
            model_name='assoc',
            name='default_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_assocs', to='band.section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('band_id', 'order'), name='band_section_unique'),
        ),
    ]
